import { defineEraShader } from "../types";

export const BITMAP_GUI_ERA_SHADERS = [
  defineEraShader({
    id: "xerox-star-bitmap-gui",
    order: 6,
    label: "Xerox Star bitmap GUI",
    introduced: 1973,
    commonUse: "early 1980s niche",
    device: "Xerox Alto / 8010 Star",
    designIntent: "Hard 1-bit proportional letters on paper-like windows.",
    recognizableTrait: "Black-on-white document cards, no anti-aliasing.",
    renderMethod: "bitmap-gui",
    reveal: "progressive",
    casePolicy: "mixed",
    cell: [16, 22],
    weight: 0.12,
    round: 0,
    tracking: 0.32,
    effects: { scan: 0, dots: 0, halo: 0.008, persistence: 0 },
    spatialAdaptation: "Flat document cards on a monochrome desktop plane.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Xerox_Star"],
  }),
  defineEraShader({
    id: "apple-macintosh-quickdraw",
    order: 10,
    label: "Macintosh QuickDraw UI",
    introduced: 1984,
    commonUse: "late 1980s onward",
    device: "Apple Macintosh, QuickDraw",
    designIntent: "Proportional 1-bit UI letters with a menu bar silhouette.",
    recognizableTrait: "Crisp black-and-white desktop text.",
    renderMethod: "bitmap-gui",
    reveal: "progressive",
    casePolicy: "mixed",
    cell: [14, 20],
    weight: 0.12,
    round: 0,
    tracking: 0.32,
    effects: { scan: 0, dots: 0, halo: 0.006, persistence: 0 },
    spatialAdaptation:
      "Flat black-and-white window planes with proportional text.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Chicago_(typeface)"],
  }),
  defineEraShader({
    id: "x11-motif-workstation",
    order: 15,
    label: "X11 / Motif workstation",
    introduced: 1987,
    commonUse: "1990s",
    device: "Unix workstations, Motif, CDE",
    designIntent: "Restrained bevels and institutional labels on grey planes.",
    recognizableTrait:
      "Flat workstation windows with crisp proportional labels.",
    renderMethod: "bitmap-gui",
    reveal: "progressive",
    casePolicy: "mixed",
    cell: [14, 22],
    weight: 0.11,
    round: 0,
    tracking: 0.32,
    effects: { scan: 0, dots: 0, halo: 0.01, persistence: 0 },
    spatialAdaptation: "Workstation window planes with restrained bevels.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Motif_(user_interface)"],
  }),
  defineEraShader({
    id: "os2-presentation-manager",
    order: 16,
    label: "OS/2 Workplace Shell",
    introduced: 1988,
    commonUse: "early–mid 1990s",
    device: "IBM OS/2 Presentation Manager",
    designIntent: "Object-desktop windows with folder-like containers.",
    recognizableTrait: "Beveled IBM UI controls, no translucency.",
    renderMethod: "bitmap-gui",
    reveal: "progressive",
    casePolicy: "mixed",
    cell: [14, 22],
    weight: 0.11,
    round: 0,
    tracking: 0.31,
    effects: { scan: 0, dots: 0, halo: 0.012, persistence: 0 },
    spatialAdaptation: "Window and object planes with restrained bevels.",
    recommended: true,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Presentation_Manager"],
  }),
] as const;
