import { defineEraShader } from "../types";

export const CHARACTER_CELL_ERA_SHADERS = [
  defineEraShader({
    id: "ibm-2260-character-crt",
    order: 4,
    label: "IBM 2260 character CRT",
    introduced: 1964,
    commonUse: "late 1960s",
    device: "IBM 2260 display station",
    designIntent:
      "An early glass terminal with a coarse buffered character grid.",
    recognizableTrait: "Soft monochrome phosphor on a small curved plane.",
    renderMethod: "character-cell",
    reveal: "block",
    casePolicy: "mixed",
    columns: 80,
    cell: [9, 16],
    weight: 0.15,
    round: 0,
    tracking: 0.34,
    effects: { scan: 0.18, dots: 1, halo: 0.1, persistence: 0.3 },
    spatialAdaptation: "A single curved CRT plane with a coarse grid.",
    recommended: false,
    confidence: "low-medium",
    sources: ["https://en.wikipedia.org/wiki/IBM_2260"],
  }),
  defineEraShader({
    id: "ibm-3270-block-terminal",
    order: 5,
    label: "IBM 3270 block green terminal",
    introduced: 1971,
    commonUse: "1970s–1990s",
    device: "IBM 3270 family",
    designIntent:
      "A monospaced green form that updates in blocks, not streams.",
    recognizableTrait: "Protected field regions and a block cursor.",
    renderMethod: "character-cell",
    reveal: "block",
    casePolicy: "upper",
    columns: 80,
    cell: [9, 16],
    weight: 0.16,
    round: 0,
    tracking: 0.34,
    effects: { scan: 0.14, dots: 0.6, halo: 0.14, persistence: 0.25 },
    spatialAdaptation:
      "A rectangular terminal plane divided into field regions.",
    recommended: true,
    confidence: "high",
    sources: ["https://en.wikipedia.org/wiki/IBM_3270"],
  }),
  defineEraShader({
    id: "home-micro-rom",
    order: 7,
    label: "Home micro ROM pixel",
    introduced: 1977,
    commonUse: "1977–mid 1980s",
    device: "Apple II, TRS-80, Commodore PET",
    designIntent: "Chunky uppercase ROM letters on a coarse tile grid.",
    recognizableTrait: "Hard 8×8 pixels, 40 columns, no lowercase.",
    renderMethod: "character-cell",
    reveal: "char-stream",
    casePolicy: "upper",
    columns: 40,
    cell: [8, 8],
    weight: 0.2,
    round: 0,
    tracking: 0.36,
    effects: { scan: 0.1, dots: 0, halo: 0.01, persistence: 0.15 },
    spatialAdaptation: "Glyphs snapped to a coarse tile grid with hard edges.",
    recommended: true,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Apple_II_series"],
  }),
  defineEraShader({
    id: "dec-vt100-ascii-terminal",
    order: 8,
    label: "VT100 phosphor terminal",
    introduced: 1978,
    commonUse: "1980s",
    device: "DEC VT100 video terminal",
    designIntent: "Streaming monospaced ASCII on a single phosphor family.",
    recognizableTrait: "Character-at-a-time reveal with a soft halo.",
    renderMethod: "character-cell",
    reveal: "char-stream",
    casePolicy: "mixed",
    columns: 80,
    cell: [9, 16],
    weight: 0.13,
    round: 0,
    tracking: 0.34,
    effects: { scan: 0.2, dots: 1, halo: 0.12, persistence: 0.4 },
    spatialAdaptation:
      "A flat terminal plane with monospaced cells and phosphor material.",
    recommended: true,
    confidence: "high",
    sources: ["https://vt100.net/docs/vt100-ug/"],
  }),
  defineEraShader({
    id: "ibm-pc-cga",
    order: 9,
    label: "IBM PC CGA text",
    introduced: 1981,
    commonUse: "1980s",
    device: "IBM PC with Color Graphics Adapter",
    designIntent: "Hard 8×8 cells from a BIOS ROM character generator.",
    recognizableTrait: "Chunky bright DOS blocks in a limited palette.",
    renderMethod: "character-cell",
    reveal: "char-stream",
    casePolicy: "mixed",
    columns: 80,
    cell: [8, 8],
    weight: 0.19,
    round: 0,
    tracking: 0.36,
    effects: { scan: 0.06, dots: 0, halo: 0.006, persistence: 0.1 },
    spatialAdaptation: "A fixed 80-column grid of hard 8×8 cells.",
    recommended: false,
    confidence: "high",
    sources: ["https://en.wikipedia.org/wiki/Color_Graphics_Adapter"],
  }),
  defineEraShader({
    id: "amiga-workbench",
    order: 11,
    label: "Amiga Workbench",
    introduced: 1985,
    commonUse: "late 1980s",
    device: "Commodore Amiga, Workbench",
    designIntent: "Chunky bitmap UI text in a small, playful palette.",
    recognizableTrait: "8×8-style bitmap letters on a coloured desktop.",
    renderMethod: "character-cell",
    reveal: "progressive",
    casePolicy: "mixed",
    columns: 80,
    cell: [8, 8],
    weight: 0.19,
    round: 0,
    tracking: 0.36,
    effects: { scan: 0.05, dots: 0, halo: 0.01, persistence: 0.12 },
    spatialAdaptation: "Simple desktop planes with hard bitmap UI text.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Amiga_Workbench"],
  }),
  defineEraShader({
    id: "ansi-bbs-dos-art",
    order: 14,
    label: "ANSI BBS art",
    introduced: 1986,
    commonUse: "late 1980s–1990s",
    device: "MS-DOS, BBS, ANSI.SYS",
    designIntent: "A screen painted with colour blocks and escape codes.",
    recognizableTrait:
      "Block borders, cursor painting, saturated 16-colour fills.",
    renderMethod: "character-cell",
    reveal: "progressive",
    casePolicy: "mixed",
    columns: 80,
    cell: [8, 16],
    weight: 0.19,
    round: 0,
    tracking: 0.36,
    effects: { scan: 0.12, dots: 0.4, halo: 0.02, persistence: 0.2 },
    spatialAdaptation: "An 80×25 canvas of cells plus block-drawing borders.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/ANSI_art"],
  }),
  defineEraShader({
    id: "ibm-pc-vga",
    order: 13,
    label: "DOS VGA console",
    introduced: 1987,
    commonUse: "late 1980s–1990s",
    device: "IBM VGA-compatible PC display",
    designIntent:
      "Crisp 9×16 DOS console cells, hard-edged even when floating.",
    recognizableTrait: "Dense orderly console text with a block cursor.",
    renderMethod: "character-cell",
    reveal: "char-stream",
    casePolicy: "mixed",
    columns: 80,
    cell: [9, 16],
    weight: 0.15,
    round: 0,
    tracking: 0.34,
    effects: { scan: 0, dots: 0, halo: 0.005, persistence: 0 },
    spatialAdaptation: "A crisp 80×25 grid with hard pixel edges.",
    recommended: true,
    confidence: "high",
    sources: ["https://en.wikipedia.org/wiki/Video_Graphics_Array"],
  }),
] as const;
