import { defineEraShader } from "../types";

export const IMPACT_ERA_SHADERS = [
  defineEraShader({
    id: "ibm-1403-line-printer",
    order: 2,
    label: "IBM 1403 line printer",
    introduced: 1959,
    commonUse: "1960s–1970s",
    device: "IBM 1403 print chain",
    designIntent: "Heavy industrial uppercase hammered a full line at a time.",
    recognizableTrait: "Green-bar continuous paper, line-at-a-time reveal.",
    renderMethod: "impact",
    reveal: "line",
    casePolicy: "upper",
    columns: 132,
    cell: [10, 16],
    weight: 0.17,
    round: 0,
    tracking: 0.33,
    effects: { scan: 0, dots: 0, halo: 0, persistence: 0 },
    spatialAdaptation:
      "A continuous green-bar sheet that advances with a mechanical snap.",
    recommended: false,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/IBM_1403"],
  }),
  defineEraShader({
    id: "teletype-asr33",
    order: 3,
    label: "Teletype paper uppercase",
    introduced: 1963,
    commonUse: "1963–late 1970s",
    device: "Teletype Model 33 ASR",
    designIntent: "Mechanical uppercase type on paper, never a screen.",
    recognizableTrait: "All-caps impact print on a floating paper strip.",
    renderMethod: "impact",
    reveal: "char-stream",
    casePolicy: "upper",
    columns: 72,
    cell: [9, 16],
    weight: 0.16,
    round: 0,
    tracking: 0.34,
    effects: { scan: 0, dots: 0, halo: 0, persistence: 0 },
    spatialAdaptation:
      "Mount glyphs on a floating paper strip with fixed columns.",
    recommended: true,
    confidence: "medium",
    sources: ["https://en.wikipedia.org/wiki/Teletype_Model_33"],
  }),
] as const;
