import { defineEraShader } from "../types";

export const OUTLINE_ERA_SHADERS = [
  defineEraShader({
    id: "postscript-laser-printing",
    order: 12,
    label: "PostScript laser page",
    introduced: 1985,
    commonUse: "late 1980s–1990s",
    device: "PostScript printers, LaserWriter-class",
    designIntent: "Crisp scalable outlines rasterised onto a finished page.",
    recognizableTrait: "Clean page composition with real margins and kerning.",
    renderMethod: "outline",
    reveal: "page",
    casePolicy: "mixed",
    cell: [48, 96],
    weight: 0.06,
    round: 1,
    tracking: 0.3,
    effects: { scan: 0, dots: 0, halo: 0.012, persistence: 0 },
    spatialAdaptation: "Finished page planes with high-resolution black type.",
    recommended: false,
    confidence: "high",
    sources: ["https://en.wikipedia.org/wiki/PostScript"],
  }),
  defineEraShader({
    id: "windows-31-truetype",
    order: 17,
    label: "TrueType desktop",
    introduced: 1992,
    commonUse: "mid 1990s onward",
    device: "Windows 3.1-era PC",
    designIntent: "Scalable office lettering on grey window chrome.",
    recognizableTrait: "Smooth proportional text in an office desktop.",
    renderMethod: "outline",
    reveal: "progressive",
    casePolicy: "mixed",
    cell: [56, 112],
    weight: 0.055,
    round: 1,
    tracking: 0.3,
    effects: { scan: 0, dots: 0, halo: 0.018, persistence: 0 },
    spatialAdaptation: "Smooth scalable text on grey desktop window planes.",
    recommended: true,
    confidence: "high",
    sources: ["https://en.wikipedia.org/wiki/TrueType"],
  }),
] as const;
